export const TECH_STACK_ITEMS = {
  llms: ["ChatGPT", "Mistral AI", "Qwen", "Gemini", "Whisper"],
  "computer-vision": ["YOLO", "OpenCV", "Faster R-CNN", "RCNN", "RT-DETRv2", "Albumentations"],
  "deep-learning": ["PyTorch", "PyTorch Lightning"],
  "data-science": ["NumPy", "Pandas"],
  "backend-storage": [
    "FastAPI",
    "SQLAlchemy",
    "Alembic",
    "Celery",
    "RabbitMQ",
    "Postgres",
    "MongoDB",
    "Redis",
    "MinIO",
    "Cloudflare Workers",
    "AWS",
  ],
  frontend: ["React", "React Native", "Next.js", "Vike", "Vite", "Tailwind CSS", "Bun"],
  "quality-delivery": [
    "Playwright",
    "Cypress",
    "Vitest",
    "Jest",
    "Pytest",
    "Testing Library",
    "Ruff",
    "Mypy",
    "Snyk",
  ],
  "languages-tools": [
    "TypeScript",
    "Python",
    "Go",
    "Rust",
    "Tauri",
    "Electron",
    "uv",
    "Bash",
    "Git",
    "Docker",
    "Docker Compose",
    "Pydantic",
    "Figma",
    "Cursor",
  ],
  "current-os": ["EndeavourOS", "Ubuntu", "Windows"],
} as const;

export type TechStackCategoryKey = keyof typeof TECH_STACK_ITEMS;
