import type { ComponentType } from "react";
import {
  SiBun,
  SiCelery,
  SiCloudflare,
  SiCloudflareworkers,
  SiCypress,
  SiDocker,
  SiDoctrine,
  SiElectron,
  SiFastapi,
  SiFigma,
  SiGit,
  SiGithubactions,
  SiGitlab,
  SiGo,
  SiGooglegemini,
  SiGrafana,
  SiHuggingface,
  SiJest,
  SiKubernetes,
  SiMinio,
  SiMistralai,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpenai,
  SiOpencv,
  SiPandas,
  SiPhp,
  SiPostgresql,
  SiPydantic,
  SiPytest,
  SiPython,
  SiPytorch,
  SiRabbitmq,
  SiReact,
  SiNvidia,
  SiRedis,
  SiRuff,
  SiRust,
  SiSnyk,
  SiSqlalchemy,
  SiSurrealdb,
  SiSymfony,
  SiTailwindcss,
  SiTauri,
  SiTestinglibrary,
  SiTypescript,
  SiJavascript,
  SiVite,
  SiVitest,
  SiYolo,
} from "react-icons/si";
import {
  Bot,
  Boxes,
  BrainCircuit,
  ChartNoAxesCombined,
  CloudCog,
  Code2,
  Crosshair,
  FileCode2,
  Gauge,
  LaptopMinimal,
  MonitorCheck,
  ShieldCheck,
  Mic,
  SearchCheck,
  Server,
  Sigma,
  Terminal,
  TestTube2,
  Wrench,
  Zap,
} from "lucide-react";
import { FaAws, FaTheaterMasks } from "react-icons/fa";
import { GiDeliveryDrone, GiThorHammer } from "react-icons/gi";
import { LuBrainCircuit } from "react-icons/lu";
import { SiK3S } from "react-icons/si";
import { OpenRouterIcon } from "@components/icons/openrouter-icon";
import { QdrantIcon } from "@components/icons/qdrant-icon";

export type TechStackIconComponent = ComponentType<{
  size?: number;
  className?: string;
  "aria-hidden"?: boolean;
}>;

export type TechStackLevel = "learning" | "comfortable" | "advanced" | "expert";
export type TechStackUsage = "daily" | "regular" | "occasional";

export type TechStackItem = {
  label: string;
  icon: TechStackIconComponent;
  iconSize?: number;
  iconClassName?: string;
  level?: TechStackLevel;
  usage?: TechStackUsage;
};

export const TECH_STACK_ITEMS = {
  TypeScript: {
    label: "TypeScript",
    icon: SiTypescript,
    iconClassName: "text-[#3178C6]",
    usage: "daily",
    level: "advanced",
  },
  JavaScript: {
    label: "JavaScript",
    icon: SiJavascript,
    iconClassName: "text-[#F0DB4F]",
    usage: "occasional",
    level: "advanced",
  },
  "Node.js": {
    label: "Node.js",
    icon: SiNodedotjs,
    iconClassName: "text-[#5FA04E]",
    usage: "regular",
    level: "advanced",
  },
  Python: {
    label: "Python",
    icon: SiPython,
    iconClassName: "text-[#3776AB]",
    usage: "daily",
    level: "advanced",
  },
  Go: {
    label: "Go",
    icon: SiGo,
    iconClassName: "text-[#00ADD8]",
    iconSize: 24,
    level: "learning",
    usage: "occasional",
  },
  Rust: {
    label: "Rust",
    icon: SiRust,
    iconClassName: "text-[#B7410E]",
    iconSize: 24,
    usage: "regular",
    level: "comfortable",
  },
  PHP: {
    label: "PHP",
    icon: SiPhp,
    iconClassName: "text-[#777BB4]",
    iconSize: 24,
    usage: "occasional",
    level: "comfortable",
  },
  Bash: {
    label: "Bash",
    icon: Terminal,
    iconClassName: "text-green-400",
    usage: "daily",
    level: "advanced",
  },
  React: {
    label: "React",
    icon: SiReact,
    iconClassName: "text-[#61DAFB]",
    usage: "daily",
    level: "comfortable",
  },
  "React Native": {
    label: "React Native",
    icon: SiReact,
    iconClassName: "text-[#61DAFB]",
    usage: "occasional",
    level: "comfortable",
  },
  Vinext: {
    label: "Vinext",
    icon: SiCloudflare,
    iconSize: 22,
    iconClassName: "text-[#F38020]",
    usage: "daily",
    level: "comfortable",
  },
  "Next.js": {
    label: "Next.js",
    icon: SiNextdotjs,
    iconClassName: "text-neutral-950 dark:text-white",
    usage: "occasional",
    level: "comfortable",
  },
  Vike: {
    label: "Vike",
    icon: GiThorHammer,
    iconClassName: "text-slate-400",
    usage: "occasional",
    level: "learning",
  },
  Vite: {
    label: "Vite",
    icon: SiVite,
    iconClassName: "text-[#646CFF]",
    usage: "daily",
    level: "comfortable",
  },
  "Tailwind CSS": {
    label: "Tailwind CSS",
    icon: SiTailwindcss,
    iconClassName: "text-[#38BDF8]",
    usage: "daily",
    level: "comfortable",
  },
  Bun: {
    label: "Bun",
    icon: SiBun,
    iconClassName: "text-neutral-900 dark:text-[#FBF0DF]",
    usage: "daily",
    level: "comfortable",
  },
  Tauri: {
    label: "Tauri",
    icon: SiTauri,
    iconClassName: "text-[#24C8DB]",
    usage: "occasional",
    level: "comfortable",
  },
  Electron: {
    label: "Electron",
    icon: SiElectron,
    iconClassName: "text-[#47848F]",
    usage: "regular",
    level: "comfortable",
  },
  FastAPI: {
    label: "FastAPI",
    icon: SiFastapi,
    iconClassName: "text-[#009688]",
    usage: "regular",
    level: "comfortable",
  },
  Pydantic: {
    label: "Pydantic",
    icon: SiPydantic,
    iconClassName: "text-[#E92063]",
    usage: "regular",
    level: "comfortable",
  },
  Doctrine: {
    label: "Doctrine",
    icon: SiDoctrine,
    iconClassName: "text-[#FC6A31]",
    usage: "occasional",
    level: "comfortable",
  },
  Symfony: {
    label: "Symfony",
    icon: SiSymfony,
    iconClassName: "text-neutral-900 dark:text-white",
    usage: "occasional",
    level: "comfortable",
  },
  SQLAlchemy: {
    label: "SQLAlchemy",
    icon: SiSqlalchemy,
    iconClassName: "text-[#D71F00]",
    usage: "regular",
    level: "learning",
  },
  Alembic: {
    label: "Alembic",
    icon: TestTube2,
    iconClassName: "text-amber-400",
    usage: "daily",
    level: "comfortable",
  },
  Celery: {
    label: "Celery",
    icon: SiCelery,
    iconClassName: "text-[#37814A]",
    usage: "regular",
    level: "comfortable",
  },
  Uvicorn: {
    label: "Uvicorn",
    icon: Server,
    iconClassName: "text-sky-400",
    usage: "regular",
    level: "comfortable",
  },
  Postgres: {
    label: "Postgres",
    icon: SiPostgresql,
    iconClassName: "text-[#4169E1]",
    usage: "daily",
    level: "advanced",
  },
  MongoDB: {
    label: "MongoDB",
    icon: SiMongodb,
    iconClassName: "text-[#47A248]",
    usage: "daily",
    level: "comfortable",
  },
  SurrealDB: {
    label: "SurrealDB",
    icon: SiSurrealdb,
    iconClassName: "text-[#FF00A0]",
    usage: "occasional",
    level: "learning",
  },
  Redis: {
    label: "Redis",
    icon: SiRedis,
    iconClassName: "text-[#DC382D]",
    iconSize: 16,
    usage: "occasional",
    level: "comfortable",
  },
  RabbitMQ: { label: "RabbitMQ", icon: SiRabbitmq, iconClassName: "text-[#FF6600]", iconSize: 16 },
  SQS: {
    label: "AWS SQS",
    icon: FaAws,
    iconClassName: "text-[#FF9900]",
    iconSize: 22,
    usage: "daily",
  },
  DLQ: { label: "AWS DLQ", icon: FaAws, iconClassName: "text-[#FF9900]", iconSize: 22 },
  MinIO: {
    label: "MinIO",
    icon: SiMinio,
    iconClassName: "text-[#C72E49]",
    iconSize: 22,
    usage: "regular",
    level: "comfortable",
  },
  Garage: {
    label: "Garage",
    icon: GiDeliveryDrone,
    iconClassName: "text-[#F38020]",
    usage: "occasional",
    level: "comfortable",
    iconSize: 22,
  },
  FalkorDB: {
    label: "FalkorDB",
    icon: Boxes,
    iconClassName: "text-amber-400",
    usage: "regular",
    level: "learning",
  },
  Kafka: { label: "Kafka", icon: Zap, iconClassName: "text-slate-400" },
  YOLO: {
    label: "YOLO",
    icon: SiYolo,
    iconClassName: "text-[#042AFF]",
    usage: "daily",
    level: "comfortable",
  },
  OpenCV: { label: "OpenCV", icon: SiOpencv, iconClassName: "text-[#5C3EE8]" },
  "Faster R-CNN": { label: "Faster R-CNN", icon: Boxes, iconClassName: "text-sky-400" },
  RCNN: { label: "RCNN", icon: SearchCheck, iconClassName: "text-cyan-400" },
  "RT-DETRv2": { label: "RT-DETRv2", icon: Crosshair, iconClassName: "text-blue-400" },
  Albumentations: {
    label: "Albumentations",
    icon: TestTube2,
    iconClassName: "text-fuchsia-400",
  },
  "Nvidia Parakeet": {
    label: "Nvidia Parakeet",
    icon: SiNvidia,
    iconClassName: "text-[#76B900]",
    usage: "occasional",
    level: "comfortable",
  },
  ChatGPT: {
    label: "ChatGPT",
    icon: SiOpenai,
    iconClassName: "text-[#10A37F]",
    usage: "daily",
    level: "advanced",
  },
  "Mistral AI": {
    label: "Mistral AI",
    icon: SiMistralai,
    iconClassName: "text-[#FF7000]",
    usage: "occasional",
    level: "advanced",
  },
  Qwen: {
    label: "Qwen",
    icon: Bot,
    iconClassName: "text-violet-400",
    usage: "occasional",
    level: "comfortable",
  },
  Gemini: {
    label: "Gemini",
    icon: SiGooglegemini,
    iconClassName: "text-[#4285F4]",
    usage: "occasional",
    level: "comfortable",
  },
  OpenRouter: {
    label: "OpenRouter",
    icon: OpenRouterIcon,
    iconClassName: "text-slate-400",
    iconSize: 26,
  },
  "AWS Bedrock": { label: "AWS Bedrock", icon: LuBrainCircuit, iconClassName: "text-[#FF9900]" },
  Whisper: {
    label: "Whisper",
    icon: Mic,
    iconClassName: "text-emerald-400",
    usage: "occasional",
    level: "comfortable",
  },
  PyTorch: { label: "PyTorch", icon: SiPytorch, iconClassName: "text-[#EE4C2C]" },
  "PyTorch Lightning": {
    label: "PyTorch Lightning",
    icon: Zap,
    iconClassName: "text-violet-400",
  },
  NumPy: { label: "NumPy", icon: SiNumpy, iconClassName: "text-[#4DABCF]" },
  Pandas: { label: "Pandas", icon: SiPandas, iconClassName: "text-[#150458]" },
  RAG: {
    label: "RAG",
    icon: SearchCheck,
    iconClassName: "text-emerald-400",
  },
  "Knowledge Retrieval": {
    label: "Knowledge Retrieval",
    icon: SearchCheck,
    iconClassName: "text-cyan-400",
  },
  "LLM Engineering": {
    label: "LLM Engineering",
    icon: BrainCircuit,
    iconClassName: "text-violet-400",
    usage: "regular",
    level: "advanced",
  },
  "Agentic Systems": {
    label: "Agentic Systems",
    icon: Bot,
    iconClassName: "text-violet-400",
    level: "advanced",
    usage: "regular",
  },
  MLOps: {
    label: "MLOps",
    icon: ChartNoAxesCombined,
    iconClassName: "text-blue-400",
  },
  "AI Infrastructure": {
    label: "AI Infrastructure",
    icon: CloudCog,
    iconClassName: "text-blue-400",
  },
  "GenAI Developer Tooling": {
    label: "GenAI Developer Tooling",
    icon: Wrench,
    iconClassName: "text-purple-400",
  },
  "Computer Vision": {
    label: "Computer Vision",
    icon: Crosshair,
    iconClassName: "text-rose-400",
  },
  "Object Detection": {
    label: "Object Detection",
    icon: Boxes,
    iconClassName: "text-red-400",
    usage: "regular",
    level: "comfortable",
  },
  Qdrant: {
    label: "Qdrant",
    icon: QdrantIcon,
    iconClassName: "text-[#DC244C]",
    usage: "regular",
    level: "comfortable",
  },
  RAGAS: { label: "RAGAS", icon: ChartNoAxesCombined, iconClassName: "text-fuchsia-400" },
  Langfuse: {
    label: "Langfuse",
    icon: Gauge,
    iconClassName: "text-amber-300",
    usage: "regular",
    level: "comfortable",
  },
  MLflow: { label: "MLflow", icon: ChartNoAxesCombined, iconClassName: "text-sky-400" },
  "HF TEI": { label: "HF TEI", icon: SiHuggingface, iconClassName: "text-[#FFD21E]" },
  "OpenAI API": { label: "OpenAI API", icon: SiOpenai, iconClassName: "text-[#10A37F]" },
  uv: {
    label: "uv",
    icon: Terminal,
    iconClassName: "text-slate-400",
    usage: "daily",
    level: "advanced",
  },
  Git: {
    label: "Git",
    icon: SiGit,
    iconClassName: "text-[#F05032]",
    usage: "daily",
    level: "advanced",
  },
  GitLab: {
    label: "GitLab",
    icon: SiGitlab,
    iconClassName: "text-[#FC6D26]",
    usage: "daily",
    level: "advanced",
  },
  K8S: {
    label: "K8S",
    icon: SiKubernetes,
    iconClassName: "text-[#326CE5]",
    usage: "daily",
    level: "comfortable",
  },
  K3S: {
    label: "K3S",
    icon: SiK3S,
    iconClassName: "text-[#ffc61c]",
    usage: "daily",
    level: "comfortable",
  },
  Docker: {
    label: "Docker",
    icon: SiDocker,
    iconClassName: "text-[#2496ED]",
    iconSize: 22,
    usage: "daily",
    level: "comfortable",
  },
  "Docker Compose": {
    label: "Docker Compose",
    icon: SiDocker,
    iconClassName: "text-[#2496ED]",
    iconSize: 22,
    usage: "daily",
    level: "comfortable",
  },
  AWS: {
    label: "AWS",
    icon: FaAws,
    iconClassName: "text-[#FF9900]",
    iconSize: 22,
    usage: "daily",
    level: "comfortable",
  },
  GCP: {
    label: "GCP",
    icon: CloudCog,
    iconClassName: "text-[#4285F4]",
    iconSize: 22,
    usage: "occasional",
    level: "learning",
  },
  Pulumi: {
    label: "Pulumi",
    icon: CloudCog,
    iconClassName: "text-violet-400",
    usage: "daily",
    level: "comfortable",
  },
  Helm: {
    label: "Helm",
    icon: SiKubernetes,
    iconClassName: "text-[#326CE5]",
    usage: "daily",
    level: "comfortable",
  },
  "Cloudflare Workers": {
    label: "Cloudflare Workers",
    icon: SiCloudflareworkers,
    iconClassName: "text-[#F38020]",
  },
  Figma: {
    label: "Figma",
    icon: SiFigma,
    iconClassName: "text-[#F24E1E]",
    usage: "occasional",
    level: "comfortable",
  },
  Playwright: {
    label: "Playwright",
    icon: FaTheaterMasks,
    iconClassName: "text-[#1D8D22]",
    usage: "daily",
    level: "expert",
  },
  Vitest: { label: "Vitest", icon: SiVitest, iconClassName: "text-[#6E9F18]" },
  "GitHub Actions": {
    label: "GitHub Actions",
    icon: SiGithubactions,
    usage: "daily",
    level: "expert",
    iconClassName: "text-[#2088FF]",
  },
  Jest: { label: "Jest", icon: SiJest, iconClassName: "text-[#C21325]" },
  Pytest: { label: "Pytest", icon: SiPytest, iconClassName: "text-[#0A9EDC]" },
  "Testing Library": {
    label: "Testing Library",
    icon: SiTestinglibrary,
    iconClassName: "text-[#E33332]",
  },
  Cypress: { label: "Cypress", icon: SiCypress, iconClassName: "text-[#69D3A7]" },
  Ruff: { label: "Ruff", icon: SiRuff, iconClassName: "text-[#D7FF64]", usage: "daily" },
  Mypy: { label: "Mypy", icon: FileCode2, iconClassName: "text-indigo-400" },
  Grafana: { label: "Grafana", icon: SiGrafana, iconClassName: "text-[#F46800]" },
  CloudWatch: { label: "CloudWatch", icon: Gauge, iconClassName: "text-[#FF9900]" },
  Snyk: {
    label: "Snyk",
    icon: SiSnyk,
    iconClassName: "text-[#4C4A73]",
    usage: "daily",
    iconSize: 22,
  },
} satisfies Record<string, TechStackItem>;

export type TechStackItemKey = keyof typeof TECH_STACK_ITEMS;
export type TechStackDomainKey = "frontend" | "backend" | "ai-data" | "platform-quality";

export type TechStackDomain = {
  key: TechStackDomainKey;
  icon: TechStackIconComponent;
  sections: readonly {
    key: string;
    icon: TechStackIconComponent;
    items: readonly TechStackItemKey[];
    wide?: boolean;
  }[];
};

export const TECH_STACK_DOMAINS: readonly TechStackDomain[] = [
  {
    key: "frontend",
    icon: Code2,
    sections: [
      {
        key: "frontend-languages-frameworks",
        icon: Code2,
        wide: true,
        items: ["TypeScript", "JavaScript", "React", "Next.js", "Vinext", "Vike", "React Native"],
      },
      { key: "build-styling", icon: Wrench, items: ["Bun", "Vite", "Tailwind CSS", "Figma"] },
      { key: "desktop", icon: LaptopMinimal, items: ["Tauri", "Electron"] },
    ],
  },
  {
    key: "backend",
    icon: Server,
    sections: [
      {
        key: "backend-languages-apis-frameworks",
        icon: Code2,
        wide: true,
        items: [
          "Python",
          "Go",
          "Rust",
          "PHP",
          "TypeScript",
          "Node.js",
          "FastAPI",
          "Pydantic",
          "SQLAlchemy",
          "Doctrine",
          "Alembic",
          "Uvicorn",
          "Symfony",
        ],
      },
      {
        key: "data-storage",
        icon: Boxes,
        items: ["Postgres", "MongoDB", "FalkorDB", "SurrealDB", "Redis", "MinIO", "Garage"],
      },
      { key: "jobs-messaging", icon: Zap, items: ["Celery", "Kafka", "RabbitMQ", "SQS", "DLQ"] },
    ],
  },
  {
    key: "ai-data",
    icon: BrainCircuit,
    sections: [
      {
        key: "ai-engineering",
        icon: BrainCircuit,
        wide: true,
        items: [
          "LLM Engineering",
          "Agentic Systems",
          "RAG",
          "Knowledge Retrieval",
          "MLOps",
          "AI Infrastructure",
          "GenAI Developer Tooling",
          "Computer Vision",
          "Object Detection",
        ],
      },
      {
        key: "models-apis",
        icon: Bot,
        items: [
          "ChatGPT",
          "Mistral AI",
          "Qwen",
          "Gemini",
          "OpenRouter",
          "AWS Bedrock",
          "OpenAI API",
        ],
      },
      {
        key: "computer-vision",
        icon: Crosshair,
        items: ["YOLO", "OpenCV", "Faster R-CNN", "RCNN", "RT-DETRv2", "Albumentations"],
      },
      {
        key: "ml-data",
        icon: Sigma,
        items: ["Python", "PyTorch", "PyTorch Lightning", "NumPy", "Pandas"],
      },
      {
        key: "retrieval",
        icon: SearchCheck,
        items: ["Qdrant", "RAGAS", "Langfuse", "MLflow", "HF TEI", "OpenAI API"],
      },
      { key: "speech", icon: Mic, items: ["Whisper", "Nvidia Parakeet"] },
    ],
  },
  {
    key: "platform-quality",
    icon: ShieldCheck,
    sections: [
      {
        key: "infrastructure-runtime",
        icon: CloudCog,
        wide: true,
        items: [
          "AWS",
          "GCP",
          "Cloudflare Workers",
          "AWS Bedrock",
          "Docker",
          "Docker Compose",
          "K8S",
          "K3S",
          "Pulumi",
        ],
      },
      {
        key: "developer-tooling",
        icon: Wrench,
        items: ["Bun", "uv", "Git", "GitLab", "Bash"],
      },
      { key: "browser-e2e", icon: MonitorCheck, items: ["Playwright", "Cypress"] },
      {
        key: "unit-code-quality",
        icon: TestTube2,
        items: ["Vitest", "Jest", "Testing Library", "Pytest", "Ruff", "Mypy"],
      },
      {
        key: "delivery-observability",
        icon: Gauge,
        items: ["GitHub Actions", "Grafana", "CloudWatch", "Langfuse", "MLflow", "Snyk"],
      },
    ],
  },
];
