/**
 * Cloudflare Worker entry point - auto-generated by vinext deploy
 * Edit freely or delete to regenerate on next deploy
 *
 * Cache backends (data + page ISR) are configured declaratively in
 * vite.config via the vinext({ cache }) option
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  isImageOptimizationPath,
} from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { buildGitHubPulse } from "../src/lib/github-pulse";
import { createFallbackLastFmNowPlaying, getLastFmNowPlaying } from "../src/lib/lastfm";

const imageConfig: ImageConfig = {
  deviceSizes: JSON.parse(
    process.env.__VINEXT_IMAGE_DEVICE_SIZES ?? JSON.stringify(DEFAULT_DEVICE_SIZES),
  ),
  imageSizes: JSON.parse(process.env.__VINEXT_IMAGE_SIZES ?? JSON.stringify(DEFAULT_IMAGE_SIZES)),
  qualities: JSON.parse(process.env.__VINEXT_IMAGE_QUALITIES ?? "null") ?? undefined,
  dangerouslyAllowSVG: process.env.__VINEXT_IMAGE_DANGEROUSLY_ALLOW_SVG === "true",
};

interface Env {
  ASSETS: Fetcher;
  LASTFM_API_KEY?: string;
  LASTFM_USERNAME?: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config
// SVG sources with .svg extension auto-skip the optimization endpoint
// on the client side (served directly, no proxy)
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

function jsonLastFmResponse(data: unknown, cacheStatus: "MISS" | "BYPASS", status = 200) {
  const CACHE_SECONDS = 30;
  const STALE_SECONDS = 60;

  return Response.json(data, {
    status,
    headers: {
      "Cache-Control": `public, max-age=0, s-maxage=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
      "CDN-Cache-Control": `public, max-age=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
      "X-Cache": cacheStatus,
    },
  });
}

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed
    if (isImageOptimizationPath(url.pathname)) {
      const allowedWidths = [
        ...(imageConfig.deviceSizes ?? DEFAULT_DEVICE_SIZES),
        ...(imageConfig.imageSizes ?? DEFAULT_IMAGE_SIZES),
      ];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths,
        imageConfig,
      );
    }

    // GitHub Pulse API - handled here because vinext v0.1.8 does not route App Router route handlers
    if (url.pathname === "/api/github/pulse" && request.method === "GET") {
      const CACHE_SECONDS = 60 * 30;
      const STALE_SECONDS = 60 * 60 * 24;
      try {
        const data = await buildGitHubPulse();
        return Response.json(data, {
          headers: {
            "Cache-Control": `public, max-age=60, s-maxage=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
            "CDN-Cache-Control": `public, max-age=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
            "X-Cache": "MISS",
          },
        });
      } catch {
        return Response.json(
          { error: "Could not load GitHub pulse", generatedAt: new Date().toISOString() },
          { status: 502 },
        );
      }
    }

    // Last.fm API - handled here for the same vinext route-handler limitation
    if (url.pathname === "/api/lastfm/now-playing" && request.method === "GET") {
      try {
        const data = await getLastFmNowPlaying({
          apiKey: env.LASTFM_API_KEY,
          user: env.LASTFM_USERNAME,
        });
        return jsonLastFmResponse(data, "MISS");
      } catch (error) {
        console.error(error);

        return jsonLastFmResponse(createFallbackLastFmNowPlaying(), "BYPASS", 502);
      }
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext()
    return handler.fetch(request, env, ctx);
  },
};
