/**
 * Cloudflare Worker entry point - auto-generated by vinext deploy
 * Edit freely or delete to regenerate on next deploy
 *
 * Cache backends (data + page ISR) are configured declaratively in
 * vite.config via the vinext({ cache }) option
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  isImageOptimizationPath,
} from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { buildGitHubPulse } from "../src/lib/github-pulse";
import { createFallbackLastFmNowPlaying, getLastFmNowPlaying } from "../src/lib/lastfm";

const imageConfig: ImageConfig = {
  deviceSizes: JSON.parse(
    process.env.__VINEXT_IMAGE_DEVICE_SIZES ?? JSON.stringify(DEFAULT_DEVICE_SIZES),
  ),
  imageSizes: JSON.parse(process.env.__VINEXT_IMAGE_SIZES ?? JSON.stringify(DEFAULT_IMAGE_SIZES)),
  qualities: JSON.parse(process.env.__VINEXT_IMAGE_QUALITIES ?? "null") ?? undefined,
  dangerouslyAllowSVG: process.env.__VINEXT_IMAGE_DANGEROUSLY_ALLOW_SVG === "true",
};

interface Env {
  ASSETS: Fetcher;
  LASTFM_API_KEY?: string;
  LASTFM_USERNAME?: string;
  PERSONAL_WEBSITE_KV_ID: KVNamespace;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config
// SVG sources with .svg extension auto-skip the optimization endpoint
// on the client side (served directly, no proxy)
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

function jsonLastFmResponse(data: unknown, cacheStatus: "MISS" | "BYPASS", status = 200) {
  const CACHE_SECONDS = 30;
  const STALE_SECONDS = 60;

  return Response.json(data, {
    status,
    headers: {
      "Cache-Control": `public, max-age=0, s-maxage=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
      "CDN-Cache-Control": `public, max-age=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
      "X-Cache": cacheStatus,
    },
  });
}

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed
    if (isImageOptimizationPath(url.pathname)) {
      const allowedWidths = [
        ...(imageConfig.deviceSizes ?? DEFAULT_DEVICE_SIZES),
        ...(imageConfig.imageSizes ?? DEFAULT_IMAGE_SIZES),
      ];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths,
        imageConfig,
      );
    }

    // GitHub Pulse API - handled here because vinext v0.1.8 does not route App Router route handlers
    if (url.pathname === "/api/github/pulse" && request.method === "GET") {
      const CACHE_SECONDS = 60 * 30;
      const STALE_SECONDS = 60 * 60 * 24;
      try {
        const data = await buildGitHubPulse();
        return Response.json(data, {
          headers: {
            "Cache-Control": `public, max-age=60, s-maxage=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
            "CDN-Cache-Control": `public, max-age=${CACHE_SECONDS}, stale-while-revalidate=${STALE_SECONDS}`,
            "X-Cache": "MISS",
          },
        });
      } catch {
        return Response.json(
          { error: "Could not load GitHub pulse", generatedAt: new Date().toISOString() },
          { status: 502 },
        );
      }
    }

    // Last.fm API - handled here for the same vinext route-handler limitation
    if (url.pathname === "/api/lastfm/now-playing" && request.method === "GET") {
      try {
        const data = await getLastFmNowPlaying({
          apiKey: env.LASTFM_API_KEY,
          user: env.LASTFM_USERNAME,
        });
        return jsonLastFmResponse(data, "MISS");
      } catch (error) {
        console.error(error);

        return jsonLastFmResponse(createFallbackLastFmNowPlaying(), "BYPASS", 502);
      }
    }

    // Endorsements GET
    if (url.pathname === "/api/endorsements" && request.method === "GET") {
      const targetId = url.searchParams.get("targetId");
      if (!targetId) {
        return Response.json({ error: "Missing targetId" }, { status: 400 });
      }
      try {
        const countStr = await env.PERSONAL_WEBSITE_KV_ID.get(`endorsements:${targetId}`);
        const count = countStr ? parseInt(countStr, 10) : 0;
        return Response.json({ count });
      } catch (error) {
        console.error("Worker KV Endorsements GET error:", error);
        return Response.json({ error: "KV read error" }, { status: 500 });
      }
    }

    // Endorsements POST
    if (url.pathname === "/api/endorsements" && request.method === "POST") {
      try {
        const body = (await request.json()) as { targetId?: string; action?: string };
        const { targetId, action } = body;
        if (!targetId) {
          return Response.json({ error: "Missing targetId" }, { status: 400 });
        }
        if (action !== "endorse" && action !== "unendorse") {
          return Response.json({ error: "Invalid action" }, { status: 400 });
        }
        const key = `endorsements:${targetId}`;
        const countStr = await env.PERSONAL_WEBSITE_KV_ID.get(key);
        const count = countStr ? parseInt(countStr, 10) : 0;

        let newCount = count;
        if (action === "endorse") {
          newCount = count + 1;
        } else if (action === "unendorse") {
          newCount = Math.max(0, count - 1);
        }

        await env.PERSONAL_WEBSITE_KV_ID.put(key, String(newCount));
        return Response.json({ count: newCount });
      } catch (error) {
        console.error("Worker KV Endorsements POST error:", error);
        return Response.json({ error: "KV write error" }, { status: 500 });
      }
    }

    // Comments GET
    if (url.pathname === "/api/comments" && request.method === "GET") {
      const targetId = url.searchParams.get("targetId");
      if (!targetId) {
        return Response.json({ error: "Missing targetId" }, { status: 400 });
      }
      try {
        const commentsStr = await env.PERSONAL_WEBSITE_KV_ID.get(`comments:${targetId}`);
        const rawComments = commentsStr
          ? (JSON.parse(commentsStr) as Array<{
              id: string;
              email: string;
              username?: string;
              body: string;
              createdAt: string;
            }>)
          : [];
        const sanitizedComments = rawComments.map((c) => {
          const hasUsername = c.username && c.username.trim().length > 0;
          return {
            id: c.id,
            displayName: hasUsername && c.username ? c.username.trim() : c.email.trim(),
            body: c.body,
            createdAt: c.createdAt,
          };
        });
        return Response.json({ comments: sanitizedComments });
      } catch (error) {
        console.error("Worker KV Comments GET error:", error);
        return Response.json({ error: "KV read error" }, { status: 500 });
      }
    }

    // Comments POST
    if (url.pathname === "/api/comments" && request.method === "POST") {
      try {
        const body = (await request.json()) as {
          targetId?: string;
          email?: string;
          username?: string;
          comment?: string;
        };
        const { targetId, email, username, comment } = body;
        if (!targetId) {
          return Response.json({ error: "Missing targetId" }, { status: 400 });
        }
        if (!email || typeof email !== "string" || !email.includes("@")) {
          return Response.json({ error: "Invalid email address" }, { status: 400 });
        }
        if (!comment || typeof comment !== "string" || comment.trim().length === 0) {
          return Response.json({ error: "Comment body cannot be empty" }, { status: 400 });
        }

        const ipHeader = request.headers.get("cf-connecting-ip") || "local";
        const ip = ipHeader.split(",")[0].trim();

        // Rate limiting: check if this email or IP has commented in the last 20 minutes
        const trimmedEmail = email.toLowerCase().trim();
        const emailKey = `ratelimit:comment:email:${trimmedEmail}`;
        const ipKey = `ratelimit:comment:ip:${ip}`;

        const [emailLimit, ipLimit] = await Promise.all([
          env.PERSONAL_WEBSITE_KV_ID.get(emailKey),
          env.PERSONAL_WEBSITE_KV_ID.get(ipKey),
        ]);

        if (emailLimit || ipLimit) {
          return Response.json(
            { error: "You can only submit one comment every 20 minutes" },
            { status: 429 },
          );
        }

        const key = `comments:${targetId}`;
        const commentsStr = await env.PERSONAL_WEBSITE_KV_ID.get(key);
        const rawComments = commentsStr
          ? (JSON.parse(commentsStr) as Array<{
              id: string;
              email: string;
              username?: string;
              body: string;
              createdAt: string;
            }>)
          : [];

        const newComment = {
          id: crypto.randomUUID(),
          email: email.trim(),
          username: username ? username.trim() : "",
          body: comment.trim(),
          createdAt: new Date().toISOString(),
        };

        rawComments.push(newComment);
        await env.PERSONAL_WEBSITE_KV_ID.put(key, JSON.stringify(rawComments));

        // Persist rate limit for 20 minutes (1200 seconds)
        const LIMIT_TTL = 20 * 60;
        await Promise.all([
          env.PERSONAL_WEBSITE_KV_ID.put(emailKey, "1", { expirationTtl: LIMIT_TTL }),
          env.PERSONAL_WEBSITE_KV_ID.put(ipKey, "1", { expirationTtl: LIMIT_TTL }),
        ]);

        return Response.json({
          success: true,
          comment: {
            id: newComment.id,
            displayName: newComment.username || newComment.email,
            body: newComment.body,
            createdAt: newComment.createdAt,
          },
        });
      } catch (error) {
        console.error("Worker KV Comments POST error:", error);
        return Response.json({ error: "KV write error" }, { status: 500 });
      }
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext()
    return handler.fetch(request, env, ctx);
  },
};
